#!/bin/bash

readonly BASH_UNIT_ROOT_DIR="$(dirname "${BASH_SOURCE[0]}")"

trap 'Console::renderResult '\
'"$(State::getTestsPassed)" '\
'"$(State::getTestsFailed)" '\
'"$(State::getAssertionsPassed)" '\
'"$(State::getAssertionsFailed)"' EXIT

source "$BASH_UNIT_ROOT_DIR/src/default_env_config.sh"
source "$BASH_UNIT_ROOT_DIR/src/env_configuration.sh"
source "$BASH_UNIT_ROOT_DIR/src/check_os.sh"
source "$BASH_UNIT_ROOT_DIR/src/state.sh"
source "$BASH_UNIT_ROOT_DIR/src/colors.sh"
source "$BASH_UNIT_ROOT_DIR/src/console_results.sh"
source "$BASH_UNIT_ROOT_DIR/src/helpers.sh"
source "$BASH_UNIT_ROOT_DIR/src/assert.sh"
source "$BASH_UNIT_ROOT_DIR/src/test_doubles.sh"

source "$BASH_UNIT_ROOT_DIR/src/runner.sh" "$@"

exit 0
