#!/bin/bash

# shellcheck disable=SC2034
_COLOR_DEFAULT=$'\e[0m'
_COLOR_BOLD=$'\e[1m'
_COLOR_FAINT=$'\e[2m'
_COLOR_FAILED=$'\e[31m'
_COLOR_PASSED=$'\e[32m'
_COLOR_SKIPPED=$'\e[33m'
_COLOR_INCOMPLETE=$'\e[36m'
_COLOR_SNAPSHOT=$'\e[34m'
_COLOR_RETURN_ERROR=$'\e[41m'
_COLOR_RETURN_SUCCESS=$'\e[42m'
_COLOR_RETURN_SKIPPED=$'\e[43m'
_COLOR_RETURN_INCOMPLETE=$'\e[46m'
_COLOR_RETURN_SNAPSHOT=$'\e[44m'
